name: 'Preserve State Action'
description: 'Preserve the workdir state in a separate branch'
inputs:
  state_name:
    description: 'The name of the state branch'
    required: true
    default: state
  main_name:
    description: 'The name of the main branch to rebase on'
    required: true
    default: main
runs:
  using: 'composite'
  steps:
    - run: git config user.name github-actions
      shell: sh
    - run: git config user.email github-actions@github.com
      shell: sh
    - run: git add -A .
      shell: sh
    - run: git commit -m "Updated State" && git push -u origin ${{ inputs.state_name }} || echo "No changes!"
      shell: sh
    - run: git push --force
      shell: sh
